version: "3.8"

services:
  analisador:
    build: ./agente-analisador
    ports:
      - "8000:8000"

  encaminhador:
    build: ./agente-encaminhador
    ports:
      - "8001:8001"

  gateway:
    build: ./gateway-api
    ports:
      - "8080:8080"
    depends_on:
      - analisador
      - encaminhador
