version: '3.8'

services:
  gateway:
    build: ./gateway-api
    ports:
      - "8080:80"
    # Modificação aqui: o gateway agora espera os serviços estarem 'saudáveis'
    depends_on:
      analisador:
        condition: service_healthy
      encaminhador:
        condition: service_healthy
    networks:
      - sistema_distribuido_net

  analisador:
    build: ./agente-analisador
    ports:
      - "8000:8000"
    networks:
      - sistema_distribuido_net
    # Adição da seção de healthcheck
    healthcheck:
      # O comando que o Docker executará para verificar a saúde
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s       # Verifica a cada 10 segundos
      timeout: 5s         # Espera 5 segundos por uma resposta
      retries: 5          # Tenta 5 vezes antes de marcar como 'unhealthy'
      start_period: 40s   # Não verifica nos primeiros 40s, dando tempo para o modelo carregar

  encaminhador:
    build: ./agente-encaminhador
    ports:
      - "8001:8001"
    networks:
      - sistema_distribuido_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  sistema_distribuido_net:
    driver: bridge
